

-- DROP TABLE IF EXISTS `sequence_data`;

CREATE TABLE `sequence_data` (
  `SeqName` varchar(50) NOT NULL,
  `SeqValue` bigint(20) NOT NULL,
  `DataInserimento` datetime NOT NULL,
  `DataAggiornamento` datetime NOT NULL,
  PRIMARY KEY (`SeqName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



-- DROP PROCEDURE IF EXISTS  `sp_SEQ_Drop` ;

DELIMITER $$
CREATE PROCEDURE `sp_SEQ_Drop`(IN seqName VARCHAR(50))
BEGIN
	SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	START TRANSACTION;
	DELETE FROM sequence_data WHERE SeqName=seqName;
	COMMIT;
END $$
DELIMITER; 


-- DROP PROCEDURE IF EXISTS  `sp_SEQ_GetNextValue`;

DELIMITER $$
CREATE PROCEDURE `sp_SEQ_GetNextValue`(IN seqName VARCHAR(50))
BEGIN
	SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	START TRANSACTION;
	
	INSERT INTO sequence_data 
		SET SeqName=seqName,
		SeqValue = LAST_INSERT_ID(1), DataInserimento=CURRENT_TIMESTAMP, DataAggiornamento=CURRENT_TIMESTAMP
	ON DUPLICATE KEY 
	UPDATE SeqValue = LAST_INSERT_ID(SeqValue + 1), DataAggiornamento=CURRENT_TIMESTAMP;
	
	COMMIT;
	SELECT LAST_INSERT_ID();
END $$
DELIMITER ;



-- DROP PROCEDURE IF EXISTS  `sp_SEQ_Reset`;

DELIMITER $$
CREATE  PROCEDURE `sp_SEQ_Reset`(IN seqName VARCHAR(50))
BEGIN
	SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	START TRANSACTION;
	
	INSERT INTO sequence_data 
		SET SeqName=seqName,
		SeqValue = 0, DataInserimento=CURRENT_TIMESTAMP, DataAggiornamento=CURRENT_TIMESTAMP
	ON DUPLICATE KEY 
	UPDATE SeqValue = LAST_INSERT_ID(0), DataAggiornamento=CURRENT_TIMESTAMP;
	
	COMMIT;
	SELECT LAST_INSERT_ID();
END $$
DELIMITER ;

